name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H 54.234.182.112 >> ~/.ssh/known_hosts || true

      - name: Start SSH Agent and Add Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Test SSH Connection with Debugging
        run: ssh -vvv -o StrictHostKeyChecking=no ec2-user@54.234.182.112 "echo 'SSH Connection Successful'"
